# jekyll config
safe:        true
lsi:         false
highlighter: pygments
markdown:    redcarpet
redcarpet:
  extensions: [tables, with_toc_data]
gems:
  - jekyll-redirect-from

# custom config
cachebust: 1